baseURL = 'https://pagi-maula.github.io'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hello-friend'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


  [params.social]
  rss            = true
  email          = "rich.youngkin@gmail.com"
  linkedin       = "https://www.linkedin.com/in/richard-youngkin-0749763"
  github         = "https://github.com/youngkin"
  medium         = "https://medium.com/@RichYoungkin"
  stackoverflow  = "https://stackoverflow.com/users/2646870/rich"
  reddit         = "https://www.reddit.com/user/elevation5280"
